#!/usr/bin/env bash

: "${VITASDK:?VITASDK is not set}"

backend="${VITASDK}/bin/pkgconf"
if [[ ! -x "${backend}" ]]; then
  if command -v pkgconf >/dev/null 2>&1; then
    backend="$(command -v pkgconf)"
  elif command -v pkg-config >/dev/null 2>&1; then
    backend="$(command -v pkg-config)"
  else
    echo >&2 "arm-vita-eabi-pkg-config: pkgconf is not installed"
    exit 127
  fi
fi

# reset pkg-config variables to ensure we're not polluted by host libraries

export PKG_CONFIG_DIR=
export PKG_CONFIG_PATH=
export PKG_CONFIG_SYSROOT_DIR=

export PKG_CONFIG_LIBDIR="${VITASDK}/arm-vita-eabi/lib/pkgconfig:${VITASDK}/arm-vita-eabi/share/pkgconfig"

[[ "${1-}" == '--version' ]] && exec "${backend}" --version
exec "${backend}" "--define-variable=VITASDK=${VITASDK}" --define-prefix --static "$@"
